# Generated by Django 2.2.1 on 2019-06-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='po_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=32)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_code', models.CharField(max_length=30)),
                ('customer_type', models.CharField(max_length=30)),
                ('customer_tag', models.CharField(max_length=30)),
                ('customer_updated_on', models.DateTimeField(auto_now_add=True)),
                ('customer_updated_by', models.CharField(max_length=30)),
            ],
        ),
    ]
