# Generated by Django 2.2.2 on 2019-06-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLegalInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectoffice.Customer')),
            ],
        ),
    ]
