# Generated by Django 2.2.2 on 2019-06-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectoffice', '0003_auto_20190613_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercommchannel',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='email',
            name='comm_id',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='comm_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='projectattributes',
            name='project_id',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customeradditionalattribute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerlegalinfo',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='CustomerCommChannel',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectAttributes',
        ),
    ]
