# Generated by Django 2.2.2 on 2019-06-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectoffice', '0004_auto_20190625_1344'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tbl_customer',
        ),
        migrations.AlterModelTable(
            name='customeradditionalattribute',
            table='tbl_additional_attribute',
        ),
        migrations.AlterModelTable(
            name='customerlegalinfo',
            table='tbl_legal_info',
        ),
    ]
