# Generated by Django 2.2.2 on 2019-06-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectoffice', '0005_auto_20190625_1619'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='projectoffice_customer',
        ),
        migrations.AlterModelTable(
            name='customeradditionalattribute',
            table='projectoffice_customeradditionalattribute',
        ),
        migrations.AlterModelTable(
            name='customerlegalinfo',
            table='projectoffice_customerlegalinfo',
        ),
    ]
