# Generated by Django 2.2.1 on 2019-06-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectoffice', '0007_auto_20190626_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customeradditionalattribute',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='customerlegalinfo',
            options={'managed': False},
        ),
    ]
