# Generated by Django 2.2.1 on 2019-06-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tblorganization',
            table='tbl_organisation',
        ),
    ]
