# Generated by Django 2.2.1 on 2019-06-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190619_1258'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbladitionalattribute',
            table='tbl_additional_attribute',
        ),
    ]
